### ISSUE TITLE
misleading meta file

### ISSUE THREAD

**Issue by kostyrev** [wunzeco/ansible-consul#1]
According to [this](https://github.com/wunzeco/ansible-consul/blob/master/tasks/main.yml#L135) the role supports only rhel7 but [meta file](https://github.com/wunzeco/ansible-consul/blob/master/meta/main.yml#L10) states rhel6 as well

**Comment by wunzeco** [comment]
Thank you for bringing it to my notice, @kostyrevaa. You are correct. The role has evolved and no longer works for rhel6.  I have update meta file to reflect this. 

Sorry, if you were misled. It wasn't intentional on my part.

**Comment by kostyrev** [comment]
Thanks!
